site_name: VNG Referentie Common Ground
site_url: https://github.com/VNG-Realisatie/referentie-common-ground


theme:
  name: material
  font:
    text: Nunito sans
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.hightlight
    - content.tabs.link
  palette:
    primary: green
    accent: teal

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  
plugins:
  - search